// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hungarian
IntegerVector hungarian(NumericMatrix cost);
RcppExport SEXP _mascarade_hungarian(SEXP costSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cost(costSEXP);
    rcpp_result_gen = Rcpp::wrap(hungarian(cost));
    return rcpp_result_gen;
END_RCPP
}
// buildBoxFit
SEXP buildBoxFit(List polysx, List polysy);
RcppExport SEXP _mascarade_buildBoxFit(SEXP polysxSEXP, SEXP polysySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type polysx(polysxSEXP);
    Rcpp::traits::input_parameter< List >::type polysy(polysySEXP);
    rcpp_result_gen = Rcpp::wrap(buildBoxFit(polysx, polysy));
    return rcpp_result_gen;
END_RCPP
}
// radialCandidates
DataFrame radialCandidates(SEXP boxfit, NumericMatrix poi, NumericVector hw, NumericVector hh, double pad, int ndir, double step, double rstart, double rmax, double intfill, double dedup);
RcppExport SEXP _mascarade_radialCandidates(SEXP boxfitSEXP, SEXP poiSEXP, SEXP hwSEXP, SEXP hhSEXP, SEXP padSEXP, SEXP ndirSEXP, SEXP stepSEXP, SEXP rstartSEXP, SEXP rmaxSEXP, SEXP intfillSEXP, SEXP dedupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type boxfit(boxfitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type poi(poiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hw(hwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hh(hhSEXP);
    Rcpp::traits::input_parameter< double >::type pad(padSEXP);
    Rcpp::traits::input_parameter< int >::type ndir(ndirSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< double >::type rstart(rstartSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< double >::type intfill(intfillSEXP);
    Rcpp::traits::input_parameter< double >::type dedup(dedupSEXP);
    rcpp_result_gen = Rcpp::wrap(radialCandidates(boxfit, poi, hw, hh, pad, ndir, step, rstart, rmax, intfill, dedup));
    return rcpp_result_gen;
END_RCPP
}
// effectiveLength
NumericVector effectiveLength(NumericVector len, NumericVector ex, NumericVector ey, NumericVector tx, NumericVector ty, IntegerVector lab, List polysx, List polysy, NumericVector cxmin, NumericVector cxmax, NumericVector cymin, NumericVector cymax, double xlo, double xhi, double ylo, double yhi);
RcppExport SEXP _mascarade_effectiveLength(SEXP lenSEXP, SEXP exSEXP, SEXP eySEXP, SEXP txSEXP, SEXP tySEXP, SEXP labSEXP, SEXP polysxSEXP, SEXP polysySEXP, SEXP cxminSEXP, SEXP cxmaxSEXP, SEXP cyminSEXP, SEXP cymaxSEXP, SEXP xloSEXP, SEXP xhiSEXP, SEXP yloSEXP, SEXP yhiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type len(lenSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lab(labSEXP);
    Rcpp::traits::input_parameter< List >::type polysx(polysxSEXP);
    Rcpp::traits::input_parameter< List >::type polysy(polysySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cxmin(cxminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cxmax(cxmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymin(cyminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymax(cymaxSEXP);
    Rcpp::traits::input_parameter< double >::type xlo(xloSEXP);
    Rcpp::traits::input_parameter< double >::type xhi(xhiSEXP);
    Rcpp::traits::input_parameter< double >::type ylo(yloSEXP);
    Rcpp::traits::input_parameter< double >::type yhi(yhiSEXP);
    rcpp_result_gen = Rcpp::wrap(effectiveLength(len, ex, ey, tx, ty, lab, polysx, polysy, cxmin, cxmax, cymin, cymax, xlo, xhi, ylo, yhi));
    return rcpp_result_gen;
END_RCPP
}
// firstLeaderHit
List firstLeaderHit(NumericVector ex, NumericVector ey, NumericVector tx, NumericVector ty, List polysx, List polysy);
RcppExport SEXP _mascarade_firstLeaderHit(SEXP exSEXP, SEXP eySEXP, SEXP txSEXP, SEXP tySEXP, SEXP polysxSEXP, SEXP polysySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< List >::type polysx(polysxSEXP);
    Rcpp::traits::input_parameter< List >::type polysy(polysySEXP);
    rcpp_result_gen = Rcpp::wrap(firstLeaderHit(ex, ey, tx, ty, polysx, polysy));
    return rcpp_result_gen;
END_RCPP
}
// forcePolish
List forcePolish(SEXP boxfit, NumericVector cx0, NumericVector cy0, NumericVector hw, NumericVector hh, NumericVector tx, NumericVector ty, List polysx, List polysy, double pad, double xlo, double xhi, double ylo, double yhi, int iters, double step, double MU, double pad_tgt, double stepmin, int con_type, bool sq);
RcppExport SEXP _mascarade_forcePolish(SEXP boxfitSEXP, SEXP cx0SEXP, SEXP cy0SEXP, SEXP hwSEXP, SEXP hhSEXP, SEXP txSEXP, SEXP tySEXP, SEXP polysxSEXP, SEXP polysySEXP, SEXP padSEXP, SEXP xloSEXP, SEXP xhiSEXP, SEXP yloSEXP, SEXP yhiSEXP, SEXP itersSEXP, SEXP stepSEXP, SEXP MUSEXP, SEXP pad_tgtSEXP, SEXP stepminSEXP, SEXP con_typeSEXP, SEXP sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type boxfit(boxfitSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cx0(cx0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cy0(cy0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hw(hwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hh(hhSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< List >::type polysx(polysxSEXP);
    Rcpp::traits::input_parameter< List >::type polysy(polysySEXP);
    Rcpp::traits::input_parameter< double >::type pad(padSEXP);
    Rcpp::traits::input_parameter< double >::type xlo(xloSEXP);
    Rcpp::traits::input_parameter< double >::type xhi(xhiSEXP);
    Rcpp::traits::input_parameter< double >::type ylo(yloSEXP);
    Rcpp::traits::input_parameter< double >::type yhi(yhiSEXP);
    Rcpp::traits::input_parameter< int >::type iters(itersSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< double >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< double >::type pad_tgt(pad_tgtSEXP);
    Rcpp::traits::input_parameter< double >::type stepmin(stepminSEXP);
    Rcpp::traits::input_parameter< int >::type con_type(con_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type sq(sqSEXP);
    rcpp_result_gen = Rcpp::wrap(forcePolish(boxfit, cx0, cy0, hw, hh, tx, ty, polysx, polysy, pad, xlo, xhi, ylo, yhi, iters, step, MU, pad_tgt, stepmin, con_type, sq));
    return rcpp_result_gen;
END_RCPP
}
// oneMoveSweepKernel
IntegerVector oneMoveSweepKernel(NumericVector cxmin, NumericVector cxmax, NumericVector cymin, NumericVector cymax, NumericVector ex, NumericVector ey, NumericVector tx, NumericVector ty, NumericVector len, List rows, IntegerVector init, int maxpass);
RcppExport SEXP _mascarade_oneMoveSweepKernel(SEXP cxminSEXP, SEXP cxmaxSEXP, SEXP cyminSEXP, SEXP cymaxSEXP, SEXP exSEXP, SEXP eySEXP, SEXP txSEXP, SEXP tySEXP, SEXP lenSEXP, SEXP rowsSEXP, SEXP initSEXP, SEXP maxpassSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cxmin(cxminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cxmax(cxmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymin(cyminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymax(cymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type len(lenSEXP);
    Rcpp::traits::input_parameter< List >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type maxpass(maxpassSEXP);
    rcpp_result_gen = Rcpp::wrap(oneMoveSweepKernel(cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass));
    return rcpp_result_gen;
END_RCPP
}
// twoMoveSweepKernel
IntegerVector twoMoveSweepKernel(NumericVector cxmin, NumericVector cxmax, NumericVector cymin, NumericVector cymax, NumericVector ex, NumericVector ey, NumericVector tx, NumericVector ty, NumericVector len, List rows, IntegerVector init, int maxpass, bool sq);
RcppExport SEXP _mascarade_twoMoveSweepKernel(SEXP cxminSEXP, SEXP cxmaxSEXP, SEXP cyminSEXP, SEXP cymaxSEXP, SEXP exSEXP, SEXP eySEXP, SEXP txSEXP, SEXP tySEXP, SEXP lenSEXP, SEXP rowsSEXP, SEXP initSEXP, SEXP maxpassSEXP, SEXP sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cxmin(cxminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cxmax(cxmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymin(cyminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymax(cymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type len(lenSEXP);
    Rcpp::traits::input_parameter< List >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type maxpass(maxpassSEXP);
    Rcpp::traits::input_parameter< bool >::type sq(sqSEXP);
    rcpp_result_gen = Rcpp::wrap(twoMoveSweepKernel(cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass, sq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mascarade_hungarian", (DL_FUNC) &_mascarade_hungarian, 1},
    {"_mascarade_buildBoxFit", (DL_FUNC) &_mascarade_buildBoxFit, 2},
    {"_mascarade_radialCandidates", (DL_FUNC) &_mascarade_radialCandidates, 11},
    {"_mascarade_effectiveLength", (DL_FUNC) &_mascarade_effectiveLength, 16},
    {"_mascarade_firstLeaderHit", (DL_FUNC) &_mascarade_firstLeaderHit, 6},
    {"_mascarade_forcePolish", (DL_FUNC) &_mascarade_forcePolish, 21},
    {"_mascarade_oneMoveSweepKernel", (DL_FUNC) &_mascarade_oneMoveSweepKernel, 12},
    {"_mascarade_twoMoveSweepKernel", (DL_FUNC) &_mascarade_twoMoveSweepKernel, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_mascarade(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
