# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hungarian (Jonker-Volgenant) assignment
#'
#' O(n^3) minimum-cost assignment on a square cost matrix. Used by the boundary seed (one
#' solve per column) to match labels to stacked slots.
#'
#' @param cost Square numeric cost matrix (`cost[i, j]` = cost of assigning row i to column j).
#' @return Integer vector `res` where `res[i]` is the 0-indexed column assigned to row i,
#'   minimising the total cost.
#' @keywords internal
hungarian <- function(cost) {
    .Call(`_mascarade_hungarian`, cost)
}

#' Build the box-fit R-tree for the cluster polygons
#'
#' Constructs a Boost.Geometry R-tree over the cluster polygon envelopes (and keeps the
#' polygons) so the candidate and polish kernels can answer "does this label box overlap any
#' cluster?" quickly. Rebuilt once per placement; the mask itself is not.
#'
#' @param polysx,polysy Lists of parallel numeric x/y vectors, one ring per cluster.
#' @return An external-pointer (`XPtr<BoxFit>`) handle to the box-fit structure.
#' @keywords internal
buildBoxFit <- function(polysx, polysy) {
    .Call(`_mascarade_buildBoxFit`, polysx, polysy)
}

#' Radial free-space label candidates
#'
#' From each cluster pole, marches `ndir` rays outward and emits a candidate box centre
#' wherever a box of the label's size (plus `pad`) is cluster-free (a BoxFit R-tree query): at
#' the near edge of every free interval and every `intfill` along wide ones. Candidates may
#' fall partly outside the viewport -- the effective-length overflow term ranks them, so a
#' crowded label can take a minimally-clipped edge slot instead of the far seed.
#'
#' @param boxfit External pointer from `buildBoxFit()`.
#' @param poi K x 2 matrix of cluster poles (the ray origins).
#' @param hw,hh Numeric per-label box half-sizes.
#' @param pad Numeric hard box clearance added around each box.
#' @param ndir Integer number of rays per pole.
#' @param step Numeric radial step along each ray.
#' @param rstart,rmax Numeric first and last radius searched.
#' @param intfill Numeric spacing of extra candidates along a wide free interval.
#' @param dedup Numeric grid size for de-duplicating nearby candidates.
#' @return A data.frame with integer `label` (1-indexed) and numeric `cx`, `cy`.
#' @keywords internal
radialCandidates <- function(boxfit, poi, hw, hh, pad, ndir, step, rstart, rmax, intfill, dedup) {
    .Call(`_mascarade_radialCandidates`, boxfit, poi, hw, hh, pad, ndir, step, rstart, rmax, intfill, dedup)
}

#' Effective length used to rank label candidates
#'
#' Per candidate, the length the optimizer minimises after the conflict counts: the base
#' leader length, plus the arc of the leader inside any FOREIGN cluster (routes leaders around
#' clusters), plus `OVERFLOW_WEIGHT` times how far the box overflows the viewport (steers
#' labels in-bounds).
#'
#' @param len Numeric base leader length per candidate.
#' @param ex,ey Numeric leader start (anchor) per candidate.
#' @param tx,ty Numeric leader target (pole) per candidate.
#' @param lab Integer 1-indexed own-cluster of each candidate.
#' @param polysx,polysy Lists of parallel numeric x/y vectors, one ring per cluster.
#' @param cxmin,cxmax,cymin,cymax Numeric padded box extents per candidate.
#' @param xlo,xhi,ylo,yhi Numeric viewport bounds (already inset by label.buffer).
#' @return Numeric vector of effective lengths, one per candidate.
#' @keywords internal
effectiveLength <- function(len, ex, ey, tx, ty, lab, polysx, polysy, cxmin, cxmax, cymin, cymax, xlo, xhi, ylo, yhi) {
    .Call(`_mascarade_effectiveLength`, len, ex, ey, tx, ty, lab, polysx, polysy, cxmin, cxmax, cymin, cymax, xlo, xhi, ylo, yhi)
}

#' Visible leader end (first mask-boundary hit)
#'
#' For each label, the leader runs from its box anchor (`ex`, `ey`) to the cluster pole
#' (`tx`, `ty`), which lies inside the cluster. The drawn leader stops at the mask boundary:
#' the first point where the anchor->pole segment crosses the label's own cluster ring. When
#' the segment does not cross the ring the leader runs all the way to the pole.
#'
#' @param ex,ey Numeric leader-start (anchor) coordinates, one per label.
#' @param tx,ty Numeric pole (leader target) coordinates, one per label.
#' @param polysx,polysy Lists of parallel numeric x/y vectors, one ring per label (its own
#'   cluster).
#' @return A list with numeric `bx`, `by`: the visible leader end, one per label.
#' @keywords internal
firstLeaderHit <- function(ex, ey, tx, ty, polysx, polysy) {
    .Call(`_mascarade_firstLeaderHit`, ex, ey, tx, ty, polysx, polysy)
}

#' Continuous force-directed label polish
#'
#' Pattern-search descent on the (squared) EFFECTIVE length under a hard conflict guard. The
#' effective length of a label is its centre-to-pole leader length, plus the arc of the leader
#' that runs inside any foreign cluster (routing leaders around clusters), plus a soft viewport
#' overflow penalty -- the same quantity the upstream `effectiveLength()` ranking minimises.
#' A box-box spacing penalty is added on top. Starting from a conflict-free layout
#' the search only accepts conflict-free neighbours (free-space check via the BoxFit R-tree),
#' so feasibility is preserved. Overflow is a SOFT term folded into the effective length, not a
#' hard clip, so an off-panel label can be walked back in-bounds and a label leaves the panel
#' only when that lowers total energy. The leader anchor rule mirrors R's `.anchorPoint()`, so
#' both the conflict guard and the foreign-cluster arc match the drawn geometry.
#'
#' @param boxfit External pointer from `buildBoxFit()` (the cluster keep-out).
#' @param cx0,cy0 Numeric starting label-centre coordinates.
#' @param hw,hh Numeric per-label box half-sizes.
#' @param tx,ty Numeric per-label pole (leader target).
#' @param polysx,polysy Lists of parallel numeric x/y vectors, one true mask ring per cluster
#'   (aligned with the labels), used for the foreign-cluster arc term.
#' @param pad Numeric hard box clearance.
#' @param xlo,xhi,ylo,yhi Numeric viewport bounds.
#' @param iters Integer iteration count.
#' @param step Numeric initial pattern-search step.
#' @param MU Numeric weight of the box-box spacing penalty.
#' @param pad_tgt Numeric target inter-box spacing.
#' @param stepmin Numeric smallest step tried before abandoning a direction.
#' @param con_type Integer leader style: 0 = "ledge" (corner), otherwise "line"/"box"/"none".
#' @param sq Logical; if `TRUE`, the length term uses the squared distance.
#' @return A list with numeric `cx`, `cy`: the polished label centres.
#' @keywords internal
forcePolish <- function(boxfit, cx0, cy0, hw, hh, tx, ty, polysx, polysy, pad, xlo, xhi, ylo, yhi, iters, step, MU, pad_tgt, stepmin, con_type, sq = TRUE) {
    .Call(`_mascarade_forcePolish`, boxfit, cx0, cy0, hw, hh, tx, ty, polysx, polysy, pad, xlo, xhi, ylo, yhi, iters, step, MU, pad_tgt, stepmin, con_type, sq)
}

#' Single-move conflict sweep
#'
#' Multi-pass Gauss-Seidel refinement. Each pass reorders labels by their current conflict
#' vector (box-box, leader-leader, leader-box, then leader length) descending, then moves each
#' to its lexicographically best candidate versus the current others (including staying put).
#' Stops when a pass makes no change.
#'
#' @param cxmin,cxmax,cymin,cymax Numeric padded box extents, one per candidate.
#' @param ex,ey Numeric leader start (anchor) per candidate.
#' @param tx,ty Numeric leader target (pole) per candidate.
#' @param len Numeric ranking length per candidate.
#' @param rows List of integer vectors: the 0-indexed candidate rows available to each label.
#' @param init Integer vector: the starting candidate index per label.
#' @param maxpass Integer cap on the number of sweeps.
#' @return Integer vector: the chosen candidate index per label.
#' @keywords internal
oneMoveSweepKernel <- function(cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass) {
    .Call(`_mascarade_oneMoveSweepKernel`, cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass)
}

#' Two-move conflict / length refinement
#'
#' Per label (heaviest leader first), picks the lexicographically best move (by change in
#' box-box, leader-leader, leader-box conflicts, then change in length) and applies it if it
#' improves. A CONFLICT-FREE label uses a length branch-and-bound: candidates are
#' length-ascending and a shorter c1 needs a partner only when exactly one other label
#' currently sits in that slot (that label is the partner -- it need not itself be in
#' conflict), with the length bound pruning the length-increasing tail -- the exact per-step
#' optimum. A CONFLICTED label drops the pruning and searches ALL pairs of candidates (this
#' label's against every other label's), driving out conflicts present in the input; only
#' conflicted labels pay this cost.
#'
#' @param cxmin,cxmax,cymin,cymax Numeric padded box extents, one per candidate.
#' @param ex,ey Numeric leader start (anchor) per candidate.
#' @param tx,ty Numeric leader target (pole) per candidate.
#' @param len Numeric ranking length per candidate.
#' @param rows List of integer vectors: the 0-indexed candidate rows available to each label.
#' @param init Integer vector: the starting candidate index per label.
#' @param maxpass Integer cap on the number of passes.
#' @param sq Logical; if `TRUE` the length objective uses the squared length.
#' @return Integer vector: the chosen candidate index per label.
#' @keywords internal
twoMoveSweepKernel <- function(cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass, sq) {
    .Call(`_mascarade_twoMoveSweepKernel`, cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass, sq)
}

